/*1.2 Primeiro Desafio da fase: Comandos DML (Data Manipulation Language)


* A) INSERT POPULANDO DEPARTAMENTO insert na tabela mc_dpto
COMERCIAL; CONTABILIDADE; ESTOQUE; FINANCEIRO; SAC (SERVIÇO DE ATENDIMENTO AO CLIENTE); RECURSOS HUMANOS (RH); LOGISTICA;

B) INSERT POPULANDO FUNCIONARIO PARA CADA DEPARTAMENTO CRIADO  

Observação, foram feitos os inserts A e B juntos, conforme abaixo.

Resposta do Comando SQL item a)
Resposta do Comando SQL item b)*/


--INSERT FUNCIONARIO COMERCIAL
INSERT INTO MC_DEPTO(CD_DEPTO, NM_DEPTO, ST_DEPTO) VALUES(SQ_MC_DEPTO.NEXTVAL, 'COMERCIAL', 'A');
INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DS_CARGO, VL_SALARIO, DT_CADASTRAMENTO, DT_NASCIMENTO)
VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, SQ_MC_DEPTO.CURRVAL, NULL, 'Rosarinho Roriz Leal', 'Inteligência Comercial', 2500, TO_DATE('01011991','DDMMYYYY'), TO_DATE('23031970','DDMMYYYY'));
INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DS_CARGO, VL_SALARIO, DT_CADASTRAMENTO, DT_NASCIMENTO)
VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, SQ_MC_DEPTO.CURRVAL, NULL, 'Rogério Canição Torquato', 'Vendedor 01', 12000, TO_DATE('20022000','DDMMYYYY'), TO_DATE('20071984','DDMMYYYY'));
INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DS_CARGO, VL_SALARIO, DT_CADASTRAMENTO, DT_NASCIMENTO)
VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, SQ_MC_DEPTO.CURRVAL, NULL, 'Jani Ferreira Calheiros', 'Consultor', 6000, TO_DATE('12122012','DDMMYYYY'), TO_DATE('12121992','DDMMYYYY'));

--INSERT FUNCIONARIO CONTABILIDADE
INSERT INTO MC_DEPTO(CD_DEPTO, NM_DEPTO, ST_DEPTO) VALUES (SQ_MC_DEPTO.NEXTVAL, 'CONTABILIDADE', 'A');
INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DS_CARGO, VL_SALARIO, DT_CADASTRAMENTO, DT_NASCIMENTO)
VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, SQ_MC_DEPTO.CURRVAL, NULL, 'Lauren Levine', 'Analista', 1100, TO_DATE('01011998','DDMMYYYY'), TO_DATE('30031970','DDMMYYYY'));
INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DS_CARGO, VL_SALARIO, DT_CADASTRAMENTO, DT_NASCIMENTO)
VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, SQ_MC_DEPTO.CURRVAL, NULL, 'Debra Blackwell', 'Auditor', 13000, TO_DATE('20022006','DDMMYYYY'), TO_DATE('20091984','DDMMYYYY'));

INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DS_CARGO, VL_SALARIO, DT_CADASTRAMENTO, DT_NASCIMENTO)
VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, SQ_MC_DEPTO.CURRVAL, NULL, 'Katherine Atkinson', 'Consultor Financeiro', 4000, TO_DATE('12102012','DDMMYYYY'), TO_DATE('11121990','DDMMYYYY'));

--INSERT COMPLETO FUNCIONARIO 
INSERT INTO MC_DEPTO(CD_DEPTO, NM_DEPTO, ST_DEPTO) VALUES (SQ_MC_DEPTO.NEXTVAL, 'ESTOQUE', 'A');
INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DS_CARGO, VL_SALARIO, DT_CADASTRAMENTO, DT_NASCIMENTO)
VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, SQ_MC_DEPTO.CURRVAL, NULL, 'Ashley White', 'Aprendiz', 1030, TO_DATE('19011997','DDMMYYYY'), TO_DATE('23031999','DDMMYYYY'));
INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DS_CARGO, VL_SALARIO, DT_CADASTRAMENTO, DT_NASCIMENTO)
VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, SQ_MC_DEPTO.CURRVAL, NULL, 'Kimberly Maynard', 'Repositor', 1300, TO_DATE('25012002','DDMMYYYY'), TO_DATE('20071973','DDMMYYYY'));
INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DS_CARGO, VL_SALARIO, DT_CADASTRAMENTO, DT_NASCIMENTO)
VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, SQ_MC_DEPTO.CURRVAL, NULL, 'Mario Becker', 'Auxiliar de Almoxarifado', 1500, TO_DATE('10012010','DDMMYYYY'), TO_DATE('01011992','DDMMYYYY'));

--INSERT FUNCIONARIO FINANCEIRO
INSERT INTO MC_DEPTO(CD_DEPTO, NM_DEPTO, ST_DEPTO) VALUES (SQ_MC_DEPTO.NEXTVAL, 'FINANCEIRO', 'A');
INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DS_CARGO, VL_SALARIO, DT_CADASTRAMENTO, DT_NASCIMENTO)
VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, SQ_MC_DEPTO.CURRVAL, NULL, 'Edwin Brooks', 'Analista Financeiro Junior', 1500, TO_DATE('01012020','DDMMYYYY'), TO_DATE('23031995','DDMMYYYY'));
INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DS_CARGO, VL_SALARIO, DT_CADASTRAMENTO, DT_NASCIMENTO)
VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, SQ_MC_DEPTO.CURRVAL, NULL, 'Regina Burton', 'Gerente Financeiro Senior', 8000, TO_DATE('20021995','DDMMYYYY'), TO_DATE('20071972','DDMMYYYY'));
INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DS_CARGO, VL_SALARIO, DT_CADASTRAMENTO, DT_NASCIMENTO)
VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, SQ_MC_DEPTO.CURRVAL, NULL, 'Kristy Leonard', 'Analista de Controladoria pleno', 4500, TO_DATE('12122015','DDMMYYYY'), TO_DATE('12121982','DDMMYYYY'));

--INSERT FUNCIONARIO SAC (SERVIÇO DE ATENDIMENTO AO CLIENTE)
INSERT INTO MC_DEPTO(CD_DEPTO, NM_DEPTO, ST_DEPTO) VALUES (SQ_MC_DEPTO.NEXTVAL, 'SAC (SERVIÇO DE ATENDIMENTO AO CLIENTE)', 'A');
INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DS_CARGO, VL_SALARIO, DT_CADASTRAMENTO, DT_NASCIMENTO)
VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, SQ_MC_DEPTO.CURRVAL, NULL, 'Courtney Martinez', 'Atendimento Help desk Junior', 1300, TO_DATE('06062021','DDMMYYYY'), TO_DATE('19091994','DDMMYYYY'));
INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DS_CARGO, VL_SALARIO, DT_CADASTRAMENTO, DT_NASCIMENTO)
VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, SQ_MC_DEPTO.CURRVAL, NULL, 'Lisa Mcdonald', 'Gerente de Costumer Sucess Senior', 6000, TO_DATE('20122015','DDMMYYYY'), TO_DATE('20101982','DDMMYYYY'));
INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DS_CARGO, VL_SALARIO, DT_CADASTRAMENTO, DT_NASCIMENTO)
VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, SQ_MC_DEPTO.CURRVAL, NULL, 'Isaiah Barajas', 'Analista de Atendimento Ao Cliente Pleno', 2500, TO_DATE('08092019','DDMMYYYY'), TO_DATE('08081990','DDMMYYYY'));


--INSERT FUNCIONARIO RECURSOS HUMANOS (RH)
INSERT INTO MC_DEPTO(CD_DEPTO, NM_DEPTO, ST_DEPTO) VALUES (SQ_MC_DEPTO.NEXTVAL, 'RECURSOS HUMANOS (RH)', 'A');
INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DS_CARGO, VL_SALARIO, DT_CADASTRAMENTO, DT_NASCIMENTO)
VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, SQ_MC_DEPTO.CURRVAL, NULL, 'Ashley Snyder', 'Consultor de RH Junior', 2500, TO_DATE('10102020','DDMMYYYY'), TO_DATE('10101993','DDMMYYYY'));
INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DS_CARGO, VL_SALARIO, DT_CADASTRAMENTO, DT_NASCIMENTO)
VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, SQ_MC_DEPTO.CURRVAL, NULL, 'Katherine Jones', 'Analista de RH Senior', 7500, TO_DATE('10122013','DDMMYYYY'), TO_DATE('20071980','DDMMYYYY'));
INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DS_CARGO, VL_SALARIO, DT_CADASTRAMENTO, DT_NASCIMENTO)
VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, SQ_MC_DEPTO.CURRVAL, NULL, 'Dylan Garcia', 'Gestor de Recrutamento pleno', 3500, TO_DATE('09092019','DDMMYYYY'), TO_DATE('09071992','DDMMYYYY'));

--INSERT FUNCIONARIO LOGISTICA
INSERT INTO MC_DEPTO(CD_DEPTO, NM_DEPTO, ST_DEPTO) VALUES (SQ_MC_DEPTO.NEXTVAL, 'LOGISTICA', 'A');
INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DS_CARGO, VL_SALARIO, DT_CADASTRAMENTO, DT_NASCIMENTO)
VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, SQ_MC_DEPTO.CURRVAL, NULL, 'Rachel Brown', 'Controller Logistico Junior', 1700, TO_DATE('01092021','DDMMYYYY'), TO_DATE('23031970','DDMMYYYY'));
INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DS_CARGO, VL_SALARIO, DT_CADASTRAMENTO, DT_NASCIMENTO)
VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, SQ_MC_DEPTO.CURRVAL, NULL, 'Michael Harrison', 'Gerente Logista Senior', 6500, TO_DATE('19022014','DDMMYYYY'), TO_DATE('20091980','DDMMYYYY'));
INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DS_CARGO, VL_SALARIO, DT_CADASTRAMENTO, DT_NASCIMENTO)
VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, SQ_MC_DEPTO.CURRVAL, NULL, 'Amber Taylor', 'Suply Chain pleno', 3000, TO_DATE('12012020','DDMMYYYY'), TO_DATE('21021992','DDMMYYYY'));


/*c) Popular todos os ESTADOS do Brasil. Selecione 5 Estados a seu critÃ©rio e associe no mÃ­nimo 2 cidades para cada Estado. Para cada cidade, associe no mÃ­nimo 1 bairro e para cada bairro, 
associe 2 endereÃ§os. Utilize nomes significativos e coerentes, de acordo com a base do Correio. Uma sugestÃ£o de link para acesso seria: https://buscacepinter.correios.com.br/app/endereco/index.php

Resposta do Comando SQL item c)
*/
     
INSERT INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('AC', 'ACRE');
INSERT INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('AP', 'AMAPÁ');
INSERT INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('AM', 'AMAZONAS');
INSERT INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('BA', 'BAHIA');
INSERT INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('CE', 'CEARÁ');
INSERT INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('DF', 'DISTRITO FEDERAL');
INSERT INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('ES', 'ESPÍRITO SANTO');
INSERT INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('GO', 'GOIÁS');
INSERT INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('MA', 'MARANHÃO');
INSERT INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('MS', 'MATO GROSSO DO SUL');
INSERT INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('PA', 'PARÁ');
INSERT INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('PB', 'PARAIBA');
INSERT INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('PR', 'PARANÁ');
INSERT INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('PE', 'PERNAMBUCO');
INSERT INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('PI', 'PIAUÍ');
INSERT INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('RJ', 'RIO DE JANEIRO');
INSERT INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('RN', 'RIO GRANDE DO NORTE');
INSERT INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('RS', 'RIO GRANDE DO SUL');
INSERT INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('RO', 'RONDÔNIA');
INSERT INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('RR', 'RORAIMA');
INSERT INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('SE', 'SERGIPE');
INSERT INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('TO', 'TOCANTINS');


/*d) Por fim, cadastre na tabela de ENDERECO FUNCIONARIO todos os funcionários com no mínimo 1 endereço para cada um. Escolha vários estados do Brasil, ou seja, um funcionário pode residir
 em mais de uma localidade, dado que a empresa Melhores Compras incentiva o trabalho em formato home office.

Observação, fizemos 5 inserts referente aos estados populados apenas para organização do grupo.

Resposta do Comando SQL item d)

*/

-- INSERT CIDADE, BAIRRO E LAGRADOURO - SÃO PAULO
INSERT INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('SP', 'SÃO PAULO');

INSERT INTO MC_CIDADE (CD_CIDADE, SG_ESTADO, NM_CIDADE, CD_IBGE, NR_DDD) VALUES (SQ_MC_CIDADE.NEXTVAL, 'SP', 'SÃO PAULO', 3550308, 011);
INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) VALUES (SQ_MC_BAIRRO.NEXTVAL, SQ_MC_CIDADE.CURRVAL, 'PQ NOVO MUNDO', 'NORTE');
INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, SQ_MC_BAIRRO.CURRVAL, 'R. Sd. Hilário Decimo Zanesco - Parque Novo Mundo, São Paulo - SP', 02189040);
INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, SQ_MC_BAIRRO.CURRVAL, 'Rua Soldado José Serafim, 27 - Parque Novo Mundo, São Paulo - SP', 02189070);
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END)
VALUES  (1,  1 , 111, 'NENHUM', TO_DATE('10012020','DDMMYYYY'), NULL, 'A');
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END)
VALUES  (2,  2 , 27, 'CASA 01', TO_DATE('13012020','DDMMYYYY'), NULL, 'A');


INSERT INTO MC_CIDADE (CD_CIDADE, SG_ESTADO, NM_CIDADE, CD_IBGE, NR_DDD) VALUES (SQ_MC_CIDADE.NEXTVAL, 'SP', 'GUARULHOS', 3518800, 011);
INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) VALUES (SQ_MC_BAIRRO.NEXTVAL, SQ_MC_CIDADE.CURRVAL, 'PQ EDU CHAVES', 'NORTE');
INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, SQ_MC_BAIRRO.CURRVAL, 'R. Rei Alberto - Parque Edu Chaves, São Paulo - SP', 02236000);
INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, SQ_MC_BAIRRO.CURRVAL, 'R. Carlos dos Santos - Parque Edu Chaves, São Paulo - SP', 02234001);
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END)
VALUES  (3,  3 , 458, 'CASA 03', TO_DATE('24012020','DDMMYYYY'), NULL, 'A');
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END)
VALUES  (4,  4 , 200, 'APTO 01', TO_DATE('30012020','DDMMYYYY'), NULL, 'A');


-- INSERT CIDADE, BAIRRO E LAGRADOURO - FLORIANOPOLIS
INSERT INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('SC', 'SANTA CATARINA');

INSERT INTO MC_CIDADE (CD_CIDADE, SG_ESTADO, NM_CIDADE, CD_IBGE, NR_DDD) VALUES (SQ_MC_CIDADE.NEXTVAL, 'SC', 'FLORIANÓPOLIS', 4205407, 048);
INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) VALUES (SQ_MC_BAIRRO.NEXTVAL, SQ_MC_CIDADE.CURRVAL, 'CAPOEIRAS', 'OESTE');
INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, SQ_MC_BAIRRO.CURRVAL, 'R. Padre Luiz Zuber, 341-153 - Capoeiras, Florianópolis - SC', 88070570);
INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, SQ_MC_BAIRRO.CURRVAL, 'R. Dr. Odilon Gallotti - Capoeiras, Florianópolis - SC', 88070480);
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END)
VALUES  (5,  5 , 12, 'NENHUM', TO_DATE('12012020','DDMMYYYY'), NULL, 'A');
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END)
VALUES  (6,  6 , 98, 'APTO 16', TO_DATE('18012020','DDMMYYYY'), NULL, 'A');


INSERT INTO MC_CIDADE (CD_CIDADE, SG_ESTADO, NM_CIDADE, CD_IBGE, NR_DDD) VALUES (SQ_MC_CIDADE.NEXTVAL, 'SC', 'BLUMENAL', 4202404, 048);
INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) VALUES (SQ_MC_BAIRRO.NEXTVAL, SQ_MC_CIDADE.CURRVAL, 'TRINDADE', 'CENTRO');
INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, SQ_MC_BAIRRO.CURRVAL, 'Av. Me. Benvenuta, 146 - Trindade, Florianópolis - SC', 88036500);
INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, SQ_MC_BAIRRO.CURRVAL, 'R. das Embaúbas, 94 - Morro da Cruz, Florianópolis - SC',88025170);
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END)
VALUES  (7,  7 , 321, 'CASA 09', TO_DATE('19012020','DDMMYYYY'), NULL, 'A');
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END)
VALUES  (8,  8 , 200, 'APTO 32', TO_DATE('15012020','DDMMYYYY'), NULL, 'A');

-- INSERT CIDADE, BAIRRO E LAGRADOURO - MINAS GERAIS
INSERT INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('MG', 'MINAS GERAIS');

INSERT INTO MC_CIDADE (CD_CIDADE, SG_ESTADO, NM_CIDADE, CD_IBGE, NR_DDD) VALUES (SQ_MC_CIDADE.NEXTVAL, 'MG', 'BELO HORIZONTE', 3106200, 031);
INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) VALUES (SQ_MC_BAIRRO.NEXTVAL, SQ_MC_CIDADE.CURRVAL, 'BURITIS', 'ZONA LESTE');
INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, SQ_MC_BAIRRO.CURRVAL, 'Rua Tereza Mota Valadares, 490-558 - Buritis, Belo Horizonte - MG', 30575160);
INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, SQ_MC_BAIRRO.CURRVAL, 'R. Silvio de Oliveira Martins, 2-140 - Buritis, Belo Horizonte - MG', 30575150);
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END)
VALUES  (9,  9 , 231, 'NENHUM', TO_DATE('20022020','DDMMYYYY'), NULL, 'A');
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END)
VALUES  (10,  10 , 333, 'NENHUM', TO_DATE('17022020','DDMMYYYY'), NULL, 'A');

INSERT INTO MC_CIDADE (CD_CIDADE, SG_ESTADO, NM_CIDADE, CD_IBGE, NR_DDD) VALUES (SQ_MC_CIDADE.NEXTVAL, 'MG', 'OURO PRETO', 3146107, 031);
INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) VALUES (SQ_MC_BAIRRO.NEXTVAL, SQ_MC_CIDADE.CURRVAL, 'AMARANTINA', 'ZONA RURAL');
INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, SQ_MC_BAIRRO.CURRVAL, 'R. Cap. Brito, 72 - Amarantina, Ouro Preto - MG', 35400000);
INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, SQ_MC_BAIRRO.CURRVAL, 'R. Santo Amaro, 38-70 - Amarantina, Ouro Preto - MG', 35400000);
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END)
VALUES  (11,  11 , 546, 'APTO 02', TO_DATE('12012020','DDMMYYYY'), NULL, 'A');
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END)
VALUES  (12,  12 , 435, 'NENHUM', TO_DATE('31012020','DDMMYYYY'), NULL, 'A');

-- INSERT CIDADE, BAIRRO E LAGRADOURO - ALAGOAS
INSERT INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('AL', 'ALAGOAS');

INSERT INTO MC_CIDADE (CD_CIDADE, SG_ESTADO, NM_CIDADE, CD_IBGE, NR_DDD) VALUES (SQ_MC_CIDADE.NEXTVAL, 'AL', 'MACEIÓ', 2704302, 082);
INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) VALUES (SQ_MC_BAIRRO.NEXTVAL, SQ_MC_CIDADE.CURRVAL, 'JATIÚCA', 'ZONA SUL');
INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, SQ_MC_BAIRRO.CURRVAL, 'Av. Luiz Ramalho de Castro, 1399-1281 - Jatiúca, Maceió - AL', 57036380);
INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, SQ_MC_BAIRRO.CURRVAL, 'Av. Dr. Júlio Marques Luz, 1227-1101 - Jatiúca, Maceió - AL, ', 57035700);
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END)
VALUES  (13,  13 , 58, 'CASA 14', TO_DATE('26012020','DDMMYYYY'), NULL, 'A');
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END)
VALUES  (14,  14 , 02, 'APTO 01', TO_DATE('23102020','DDMMYYYY'), NULL, 'A');


INSERT INTO MC_CIDADE (CD_CIDADE, SG_ESTADO, NM_CIDADE, CD_IBGE, NR_DDD) VALUES (SQ_MC_CIDADE.NEXTVAL, 'AL', 'MARAGOGI', 2704500, 082);
INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) VALUES (SQ_MC_BAIRRO.NEXTVAL, SQ_MC_CIDADE.CURRVAL, 'BURGALHAU', 'ZONA NORTE');
INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, SQ_MC_BAIRRO.CURRVAL, 'R. Tribo Aimorés - Barra Grande, Maragogi - AL', 57955000);
INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, SQ_MC_BAIRRO.CURRVAL, 'R. Artur Ramos de Araujo Pereira - Barra Grande, Maragogi - AL', 57955000);
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END)
VALUES  (15, 15 , 42, 'CASA 02', TO_DATE('18072020','DDMMYYYY'), NULL, 'A');
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END)
VALUES  (16,  16 , 20, 'APTO 45', TO_DATE('13032020','DDMMYYYY'), NULL, 'A');

-- INSERT CIDADE, BAIRRO E LAGRADOURO - MATO GROSSO
INSERT INTO MC_ESTADO (SG_ESTADO, NM_ESTADO) VALUES ('MT', 'MATO GROSSO');

INSERT INTO MC_CIDADE (CD_CIDADE, SG_ESTADO, NM_CIDADE, CD_IBGE, NR_DDD) VALUES (SQ_MC_CIDADE.NEXTVAL, 'MT', 'CUIABÁ', 5103403, 065);
INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) VALUES (SQ_MC_BAIRRO.NEXTVAL, SQ_MC_CIDADE.CURRVAL, 'JARDIM DOS IPÊS', 'ZONA SUL');
INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, SQ_MC_BAIRRO.CURRVAL, 'R. do Pombo Correio, 244-356 - Jardim dos Ipes, São Paulo - SP', 08160142);
INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, SQ_MC_BAIRRO.CURRVAL, 'R. Caninana, 902-1084 - Jardim Noemia, São Paulo - SP', 08180090);
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END)
VALUES  (17,  17 , 48, 'CASA 23', TO_DATE('23042020','DDMMYYYY'), NULL, 'A');
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END)
VALUES  (18,  18 , 987, 'APTO 123', TO_DATE('20032020','DDMMYYYY'), NULL, 'A');

INSERT INTO MC_CIDADE (CD_CIDADE, SG_ESTADO, NM_CIDADE, CD_IBGE, NR_DDD) VALUES (SQ_MC_CIDADE.NEXTVAL, 'MT', 'JUÍNA',   5105150, 065);
INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) VALUES (SQ_MC_BAIRRO.NEXTVAL, SQ_MC_CIDADE.CURRVAL, 'MODULO 5', 'ZONA NORTE');
INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, SQ_MC_BAIRRO.CURRVAL, 'R. Duarte da Costa, 277-143 - Palmiteira, Juína - MT', 78320000);
INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, SQ_MC_BAIRRO.CURRVAL, 'R. Figueiras, 390 - Juina, Juína - MT', 78320000);
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END)
VALUES  (19,  19 , 4582, 'CASA 13', TO_DATE('23012020','DDMMYYYY'), NULL, 'A');
INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END)
VALUES  (20,  20 , 2003, 'APTO 21', TO_DATE('18012020','DDMMYYYY'), NULL, 'A');


/* e) Cadastre no mínimo 10 CLIENTES PESSOAS FÍSICAS e 5 CLIENTES PESSOA JÚRIDICA e associe no mínimo 1 endereço para cada cliente. Utilize nomes significativos e relevantes. 

Resposta do Comando SQL item e)

*/

--INSERT CLIENTE PESSOA FISICO

INSERT INTO MC_CLIENTE (NR_CLIENTE, NM_CLIENTE, QT_ESTRELAS, VL_MEDIO_COMPRA, ST_CLIENTE, DS_EMAIL, NR_TELEFONE, NM_LOGIN, DS_SENHA) 
VALUES (SQ_MC_CLIENTE.NEXTVAL,  'Charlie Brown Junior', 9, 1230, 'I', 'chorao@gmail.com', 013912345654, 'Chorão', 'soosloucossabem' );
INSERT INTO MC_CLI_FISICA (NR_CLIENTE, DT_NASCIMENTO, FL_SEXO_BIOLOGICO, DS_GENERO, NR_CPF) 
VALUES (SQ_MC_CLIENTE.CURRVAL, TO_DATE('09041970','DDMMYYYY'), 'M', 'HETEROSSEXUAL', 87608470850);
INSERT INTO MC_CIDADE (CD_CIDADE, SG_ESTADO, NM_CIDADE, CD_IBGE, NR_DDD) VALUES (SQ_MC_CIDADE.NEXTVAL, 'SP', 'SANTOS',   3548500, 013);
INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) VALUES (SQ_MC_BAIRRO.NEXTVAL, SQ_MC_CIDADE.CURRVAL, 'GONZAGA', 'ZONA NOROESTE');
INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, SQ_MC_BAIRRO.CURRVAL, 'Av. Ana Costa - Gonzaga, Santos - SP', 11060002);
INSERT INTO MC_END_CLI (NR_CLIENTE, CD_LOGRADOURO_CLI, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) VALUES (1,  20, 100, 'CASA 01', TO_DATE('18012020','DDMMYYYY'), NULL, 'A');

INSERT INTO MC_CLIENTE (NR_CLIENTE, NM_CLIENTE, QT_ESTRELAS, VL_MEDIO_COMPRA, ST_CLIENTE, DS_EMAIL, NR_TELEFONE, NM_LOGIN, DS_SENHA) 
VALUES (SQ_MC_CLIENTE.NEXTVAL,  'Márcia Analu Lorena Drumond', 8, 2000, 'A', 'marciaanalu@gmail.com', 011941448819, 'malu', 'malu123' );
INSERT INTO MC_CLI_FISICA (NR_CLIENTE, DT_NASCIMENTO, FL_SEXO_BIOLOGICO, DS_GENERO, NR_CPF) 
VALUES (SQ_MC_CLIENTE.CURRVAL, TO_DATE('23022003','DDMMYYYY'), 'F', 'HETEROSSEXUAL', 16074735859);
INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) VALUES (SQ_MC_BAIRRO.NEXTVAL, 2, 'CIDADE INDUSTRIAL SATÉLITE DE SÃO PAULO', 'ZONA OESTE');
INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, SQ_MC_BAIRRO.CURRVAL, 'Rua Itatiaiuçu - CIDADE INDUSTRIAL SATÉLITE DE SÃO PAULO, GUARULHOS - SP', 3518800);
INSERT INTO MC_END_CLI (NR_CLIENTE, CD_LOGRADOURO_CLI, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) VALUES (2,  21, 12, 'CASA 12', TO_DATE('2012020','DDMMYYYY'), NULL, 'A');

INSERT INTO MC_CLIENTE (NR_CLIENTE, NM_CLIENTE, QT_ESTRELAS, VL_MEDIO_COMPRA, ST_CLIENTE, DS_EMAIL, NR_TELEFONE, NM_LOGIN, DS_SENHA) 
VALUES (SQ_MC_CLIENTE.NEXTVAL,  'Raquel Laís Malu Pires', 9, 4000, 'I', 'qquel@gmail.com', 48996602106, 'quelzinha11', 'paz123' );
INSERT INTO MC_CLI_FISICA (NR_CLIENTE, DT_NASCIMENTO, FL_SEXO_BIOLOGICO, DS_GENERO, NR_CPF) 
VALUES (SQ_MC_CLIENTE.CURRVAL, TO_DATE('01022003','DDMMYYYY'), 'F', 'HOMOSSEXUAL', 82559366967);
INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) VALUES (SQ_MC_BAIRRO.NEXTVAL, 3, 'SACO GRANDE', 'ZONA NORTE');
INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, SQ_MC_BAIRRO.CURRVAL, 'Rodovia Virgílio Várzea - SACO GRANDE, FLORIANÓPOLIS - SC', 4205407);
INSERT INTO MC_END_CLI (NR_CLIENTE, CD_LOGRADOURO_CLI, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) VALUES (3,  22, 12, 'CASA 12', TO_DATE('1212020','DDMMYYYY'), NULL, 'A');

INSERT INTO MC_CLIENTE (NR_CLIENTE, NM_CLIENTE, QT_ESTRELAS, VL_MEDIO_COMPRA, ST_CLIENTE, DS_EMAIL, NR_TELEFONE, NM_LOGIN, DS_SENHA) 
VALUES (SQ_MC_CLIENTE.NEXTVAL,  'Isabelly Fabiana de Paula', 9, 4500, 'A', 'isabellyfa@gmail.com', 47984274397, 'fabis12', '123gilu' );
INSERT INTO MC_CLI_FISICA (NR_CLIENTE, DT_NASCIMENTO, FL_SEXO_BIOLOGICO, DS_GENERO, NR_CPF) 
VALUES (SQ_MC_CLIENTE.CURRVAL, TO_DATE('25031998','DDMMYYYY'), 'F', 'HETEROSSEXUAL', 73260449965);
INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) VALUES (SQ_MC_BAIRRO.NEXTVAL, 4, 'GARCIA', 'ZONA SUL');
INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, SQ_MC_BAIRRO.CURRVAL, 'Rua Nereu Oliveira Basílio - GARCIA, BLUMENAU - SC', 4202404);
INSERT INTO MC_END_CLI (NR_CLIENTE, CD_LOGRADOURO_CLI, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) VALUES (4,  23, 109, 'APTO 12', TO_DATE('2309020','DDMMYYYY'), NULL, 'A');

INSERT INTO MC_CLIENTE (NR_CLIENTE, NM_CLIENTE, QT_ESTRELAS, VL_MEDIO_COMPRA, ST_CLIENTE, DS_EMAIL, NR_TELEFONE, NM_LOGIN, DS_SENHA) 
VALUES (SQ_MC_CLIENTE.NEXTVAL,  'Cecília Rafaela Valentina Bernardes', 5, 2300, 'I', 'cecebernar02@gmail.com', 31994774659, 'cili22', 'valen1123' );
INSERT INTO MC_CLI_FISICA (NR_CLIENTE, DT_NASCIMENTO, FL_SEXO_BIOLOGICO, DS_GENERO, NR_CPF) 
VALUES (SQ_MC_CLIENTE.CURRVAL, TO_DATE('25031994','DDMMYYYY'), 'F', 'HETEROSSEXUAL', 40550873651);
INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) VALUES (SQ_MC_BAIRRO.NEXTVAL, 5, 'MANGABEIRAS', 'ZONA SUL');
INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, SQ_MC_BAIRRO.CURRVAL, 'Rua Itacolomi - Mangabeiras, Belo Horizonte - MG', 3106200);
INSERT INTO MC_END_CLI (NR_CLIENTE, CD_LOGRADOURO_CLI, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) VALUES (5,  24, 1223, 'CASA 02', TO_DATE('2712020','DDMMYYYY'), NULL, 'A');

INSERT INTO MC_CLIENTE (NR_CLIENTE, NM_CLIENTE, QT_ESTRELAS, VL_MEDIO_COMPRA, ST_CLIENTE, DS_EMAIL, NR_TELEFONE, NM_LOGIN, DS_SENHA) 
VALUES (SQ_MC_CLIENTE.NEXTVAL,  'Theo Luan dos Santos', 3, 1230, 'A', 'theolus@gmail.com', 31982130818, 'lusantos', 'santos1333' );
INSERT INTO MC_CLI_FISICA (NR_CLIENTE, DT_NASCIMENTO, FL_SEXO_BIOLOGICO, DS_GENERO, NR_CPF) 
VALUES (SQ_MC_CLIENTE.CURRVAL, TO_DATE('13041998','DDMMYYYY'), 'H', 'HETEROSSEXUAL', 60608178667);
INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) VALUES (SQ_MC_BAIRRO.NEXTVAL, 6, 'VILA SAMARCO', 'CENTRO');
INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, SQ_MC_BAIRRO.CURRVAL, 'Rua Topázio, VILA SAMARCO, OURO PRETO - MG', 3146107);
INSERT INTO MC_END_CLI (NR_CLIENTE, CD_LOGRADOURO_CLI, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) VALUES (6,  25, 1231, 'APTO 03', TO_DATE('2304020','DDMMYYYY'), NULL, 'A');

INSERT INTO MC_CLIENTE (NR_CLIENTE, NM_CLIENTE, QT_ESTRELAS, VL_MEDIO_COMPRA, ST_CLIENTE, DS_EMAIL, NR_TELEFONE, NM_LOGIN, DS_SENHA) 
VALUES (SQ_MC_CLIENTE.NEXTVAL,  'Vitor Renato Mendes', 6, 2999, 'I', 'vicremendes@gmail.com', 82986500701, 'vicre222', '9229392cc' );
INSERT INTO MC_CLI_FISICA (NR_CLIENTE, DT_NASCIMENTO, FL_SEXO_BIOLOGICO, DS_GENERO, NR_CPF) 
VALUES (SQ_MC_CLIENTE.CURRVAL, TO_DATE('09041970','DDMMYYYY'), 'H', 'HETEROSSEXUAL', 38272377420);
INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) VALUES (SQ_MC_BAIRRO.NEXTVAL, 7, 'OURO PRETO', 'ZONA NORTE');
INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, SQ_MC_BAIRRO.CURRVAL, '1ª Travessa São Francisco - OURO PRETO, MACEIÓ - AL', 2704302);
INSERT INTO MC_END_CLI (NR_CLIENTE, CD_LOGRADOURO_CLI, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) VALUES (7,  26, 121, 'NENHUM', TO_DATE('1906020','DDMMYYYY'), NULL, 'A');

INSERT INTO MC_CLIENTE (NR_CLIENTE, NM_CLIENTE, QT_ESTRELAS, VL_MEDIO_COMPRA, ST_CLIENTE, DS_EMAIL, NR_TELEFONE, NM_LOGIN, DS_SENHA) 
VALUES (SQ_MC_CLIENTE.NEXTVAL,  'Sueli Isabella Rezende', 9, 6000, 'A', 'su_isa@gmail.com', 82996149221, 'isa111', '11su' );
INSERT INTO MC_CLI_FISICA (NR_CLIENTE, DT_NASCIMENTO, FL_SEXO_BIOLOGICO, DS_GENERO, NR_CPF) 
VALUES (SQ_MC_CLIENTE.CURRVAL, TO_DATE('09041970','DDMMYYYY'), 'F', 'HETEROSSEXUAL', 87608470850);
INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) VALUES (SQ_MC_BAIRRO.NEXTVAL, 8, 'CENTRO', 'ZONA CENTRAL');
INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, SQ_MC_BAIRRO.CURRVAL, 'Rua Luiz Holanda Cavalcante, s/n, 425 - 12º andar - CENTRO, MARAGOGI - AL', 2704500);
INSERT INTO MC_END_CLI (NR_CLIENTE, CD_LOGRADOURO_CLI, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) VALUES (8,  26,324, 'APTO 01', TO_DATE('3001020','DDMMYYYY'), NULL, 'A');

INSERT INTO MC_CLIENTE (NR_CLIENTE, NM_CLIENTE, QT_ESTRELAS, VL_MEDIO_COMPRA, ST_CLIENTE, DS_EMAIL, NR_TELEFONE, NM_LOGIN, DS_SENHA) 
VALUES (SQ_MC_CLIENTE.NEXTVAL,  'Eduardo Thiago Ricardo Almeida', 9, 4000, 'I', 'edurichard@gmail.com', 65986746343, 'ricardal12', 'alemiida133' );
INSERT INTO MC_CLI_FISICA (NR_CLIENTE, DT_NASCIMENTO, FL_SEXO_BIOLOGICO, DS_GENERO, NR_CPF) 
VALUES (SQ_MC_CLIENTE.CURRVAL, TO_DATE('09041970','DDMMYYYY'), 'H', 'HETEROSSEXUAL', 87608470850);
INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) VALUES (SQ_MC_BAIRRO.NEXTVAL, 9, 'JARDIM SANTA AMÁLIA', 'ZONA SUDOESTE');
INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, SQ_MC_BAIRRO.CURRVAL, 'Rua Arara Azul - JARDIM SANTA AMÁLIA, CUIABÁ - MT', 5103403);
INSERT INTO MC_END_CLI (NR_CLIENTE, CD_LOGRADOURO_CLI, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) VALUES (9,  27, 11, 'APTO 42', TO_DATE('2104020','DDMMYYYY'), NULL, 'A');

INSERT INTO MC_CLIENTE (NR_CLIENTE, NM_CLIENTE, QT_ESTRELAS, VL_MEDIO_COMPRA, ST_CLIENTE, DS_EMAIL, NR_TELEFONE, NM_LOGIN, DS_SENHA) 
VALUES (SQ_MC_CLIENTE.NEXTVAL,  'Thiago da Silva Almeida', 9, 2500, 'A', 'tigassilvahuebr@gmail.com', 6532321122, 'tigaa', 'silva1212' );
INSERT INTO MC_CLI_FISICA (NR_CLIENTE, DT_NASCIMENTO, FL_SEXO_BIOLOGICO, DS_GENERO, NR_CPF) 
VALUES (SQ_MC_CLIENTE.CURRVAL, TO_DATE('01012000','DDMMYYYY'), 'H', 'HETEROSSEXUAL', 76218668533);
INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) VALUES (SQ_MC_BAIRRO.NEXTVAL, 9, 'JARDIM SANTA AMÁLIA', 'ZONA SUDOESTE');
INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, SQ_MC_BAIRRO.CURRVAL, 'Rua Coletora - Barra do Pari, Cuiabá - MT, ', 78035410);
INSERT INTO MC_END_CLI (NR_CLIENTE, CD_LOGRADOURO_CLI, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO, ST_END) VALUES (10,  28, 03,'Nenhum', TO_DATE('2104020','DDMMYYYY'), NULL, 'A');

--INSERT CLIENTE PESSOA JURIDICA

INSERT INTO MC_CLIENTE (NR_CLIENTE, NM_CLIENTE, QT_ESTRELAS, VL_MEDIO_COMPRA, ST_CLIENTE, DS_EMAIL, NR_TELEFONE, NM_LOGIN, DS_SENHA) 
VALUES (SQ_MC_CLIENTE.NEXTVAL,  'Giovanni e Bruno Restaurante Ltda', 9, 8000, 'A', 'financeiro@giovanniebrunorestauranteltda.com.br', 1329770005, 'giovanbru', 'masterchef123' );
INSERT INTO MC_CLI_JURIDICA (NR_CLIENTE, DT_FUNDACAO, NR_CNPJ, NR_INSCR_EST) 
VALUES (SQ_MC_CLIENTE.CURRVAL, TO_DATE('25022016','DDMMYYYY'), 99985811000156, 422541132500);
INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) VALUES (SQ_MC_BAIRRO.NEXTVAL, 1, 'VILA CASCATINHA', 'ZONA SUL');
INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, SQ_MC_BAIRRO.CURRVAL, 'Rua Major Eugênio Terral, 848 - 1º andar - VILA CASCATINHA, SÃO VICENTE - SP', 3551009);

INSERT INTO MC_CLIENTE (NR_CLIENTE, NM_CLIENTE, QT_ESTRELAS, VL_MEDIO_COMPRA, ST_CLIENTE, DS_EMAIL, NR_TELEFONE, NM_LOGIN, DS_SENHA) 
VALUES (SQ_MC_CLIENTE.NEXTVAL,  'Bárbara e Evelyn Casa Noturna ME', 8, 5000, 'I', 'suporte@barbaraeevelyncasanoturname.com.br', 4826544183, 'noturnacasa', 'noturn231231' );
INSERT INTO MC_CLI_JURIDICA (NR_CLIENTE, DT_FUNDACAO, NR_CNPJ, NR_INSCR_EST) 
VALUES (SQ_MC_CLIENTE.CURRVAL, TO_DATE('11102013','DDMMYYYY'), 17903188000180, 154844659);
INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) VALUES (SQ_MC_BAIRRO.NEXTVAL, 3, 'INGLESES DO RIO VERMELHO', 'ZONA NORTE');
INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, SQ_MC_BAIRRO.CURRVAL, 'Rua Condomínio União, 811 - GALPAO - INGLESES DO RIO VERMELHO, FLORIANÓPOLIS - SC', 4205407);

INSERT INTO MC_CLIENTE (NR_CLIENTE, NM_CLIENTE, QT_ESTRELAS, VL_MEDIO_COMPRA, ST_CLIENTE, DS_EMAIL, NR_TELEFONE, NM_LOGIN, DS_SENHA) 
VALUES (SQ_MC_CLIENTE.NEXTVAL,  'Raul e Victor Joalheria Ltda', 8, 7000, 'A', 'ti@raulevictorjoalherialtda.com.br', 3137187481, 'joias', 'joiasdotanos' );
INSERT INTO MC_CLI_JURIDICA (NR_CLIENTE, DT_FUNDACAO, NR_CNPJ, NR_INSCR_EST) 
VALUES (SQ_MC_CLIENTE.CURRVAL, TO_DATE('12012013','DDMMYYYY'), 16347460000120, 6750961417120);
INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) VALUES (SQ_MC_BAIRRO.NEXTVAL, 5, 'BONSUCESSO BARREIRO', 'ZONA SUDOESTE');
INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, SQ_MC_BAIRRO.CURRVAL, 'Rua Pastor José Rufino, 896 - LOJA - BONSUCESSO BARREIROM, BELO HORIZONTE - MG', 3106200);

INSERT INTO MC_CLIENTE (NR_CLIENTE, NM_CLIENTE, QT_ESTRELAS, VL_MEDIO_COMPRA, ST_CLIENTE, DS_EMAIL, NR_TELEFONE, NM_LOGIN, DS_SENHA) 
VALUES (SQ_MC_CLIENTE.NEXTVAL,  'Giovanna e Renato Adega Ltda', 4, 4000, 'A', 'cobranca@giovannaerenatoadegaltda.com.br', 8227647697, 'degas', 'degasdarua' );
INSERT INTO MC_CLI_JURIDICA (NR_CLIENTE, DT_FUNDACAO, NR_CNPJ, NR_INSCR_EST) 
VALUES (SQ_MC_CLIENTE.CURRVAL, TO_DATE('22052018','DDMMYYYY'), 22127963000193, 248456687);
INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) VALUES (SQ_MC_BAIRRO.NEXTVAL, 7, 'FEITOSA', 'ZONA NORTE');
INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, SQ_MC_BAIRRO.CURRVAL, 'Rua Senador Rui Palmeira, 664 - LOJA - FEITOSA, MACEIÓ - AL', 2704302);

INSERT INTO MC_CLIENTE (NR_CLIENTE, NM_CLIENTE, QT_ESTRELAS, VL_MEDIO_COMPRA, ST_CLIENTE, DS_EMAIL, NR_TELEFONE, NM_LOGIN, DS_SENHA) 
VALUES (SQ_MC_CLIENTE.NEXTVAL,  'Marcela e Gael Entregas Expressas ME', 3, 3000, 'A', 'treinamento@marcelaegaelentregasexpressasme.com.br', 6528319891, 'treinerma', 'maema13232' );
INSERT INTO MC_CLI_JURIDICA (NR_CLIENTE, DT_FUNDACAO, NR_CNPJ, NR_INSCR_EST) 
VALUES (SQ_MC_CLIENTE.CURRVAL, TO_DATE('14112019','DDMMYYYY'), 30998770000136, 14062891030);
INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) VALUES (SQ_MC_BAIRRO.NEXTVAL, 9, 'CANJICA', 'ZONA OESTE');
INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, SQ_MC_BAIRRO.CURRVAL, 'Rua Três de Junho, 902 - 2º andar - CANJICA - CUIABÁ - MT', 5103403);


/*f) Cadastre um novo cliente que já tenha um mesmo login já criado. (*Exiba a instrução SQL executada para realizar a tarefa e apresente 
o resultado dessa execução). Foi possível incluir esse novo cliente? Explique?

Resposta do Comando SQL item f)

INSERT INTO MC_CLIENTE (NR_CLIENTE, NM_CLIENTE, QT_ESTRELAS, VL_MEDIO_COMPRA, ST_CLIENTE, DS_EMAIL, NR_TELEFONE, NM_LOGIN, DS_SENHA) 
VALUES (SQ_MC_CLIENTE.NEXTVAL,  'Diego Maldorado', 4, 120, 'A', 'diegomaldorado@gmail.com', 013911112222, 'Chorão', '11002200' );
INSERT INTO MC_CLI_FISICA (NR_CLIENTE, DT_NASCIMENTO, FL_SEXO_BIOLOGICO, DS_GENERO, NR_CPF) 
VALUES (SQ_MC_CLIENTE.CURRVAL, TO_DATE('09041970','DDMMYYYY'), 'H', 'HETEROSSEXUAL', 87608470850);
INSERT INTO MC_CIDADE (CD_CIDADE, SG_ESTADO, NM_CIDADE, CD_IBGE, NR_DDD) VALUES (SQ_MC_CIDADE.NEXTVAL, 'SP', 'SANTOS',   3548500, 013);
INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) VALUES (SQ_MC_BAIRRO.NEXTVAL, SQ_MC_CIDADE.CURRVAL, 'GONZAGA', 'ZONA NOROESTE');
INSERT INTO MC_LOGRADOURO (CD_LOGRADOURO, CD_BAIRRO, NM_LOGRADOURO, NR_CEP) VALUES (SQ_MC_LOGRADOURO.NEXTVAL, SQ_MC_BAIRRO.CURRVAL, 'Av. Ana Costa, 471 - 7º andar - Gonzaga, Santos - SP', 11060002);


Relatório de erros - ORA-00001: restrição exclusiva (RM551834.UK_MC_CLIENTE_MM_LOGIN) violada 

Resposta: Isso ocorre porque a restrição impede que haja valores duplicados na coluna "NM_LOGIN" da tabela "MC_CLIENTE".*/

/*g) Cadastre as seguintes categorias para os produtos: 
Artesanato; Áudio; Brinquedos; Celular e Smartphone; Colchões; Esporte e Lazer; Ferramentas; Games; Informática; Livros; Pet Shop; TV e Utilidades Domésticas.

Resposta do Comando SQL item g)

*/

INSERT INTO MC_CATEGORIA_PROD (CD_CATEGORIA, TP_CATEGORIA, DS_CATEGORIA, DT_INICIO, DT_TERMINO, ST_CATEGORIA) 
VALUES (SQ_MC_CATEGORIA.NEXTVAL, 'P', 'Artesanato', TO_DATE('01012000','DDMMYYYY'), NULL, 'A');

INSERT INTO MC_CATEGORIA_PROD (CD_CATEGORIA, TP_CATEGORIA, DS_CATEGORIA, DT_INICIO, DT_TERMINO, ST_CATEGORIA) 
VALUES (SQ_MC_CATEGORIA.NEXTVAL, 'P', 'Áudio', TO_DATE('01022000','DDMMYYYY'), NULL, 'A');

INSERT INTO MC_CATEGORIA_PROD (CD_CATEGORIA, TP_CATEGORIA, DS_CATEGORIA, DT_INICIO, DT_TERMINO, ST_CATEGORIA) 
VALUES (SQ_MC_CATEGORIA.NEXTVAL, 'P', 'Brinquedos', TO_DATE('01032000','DDMMYYYY'), NULL, 'A');

INSERT INTO MC_CATEGORIA_PROD (CD_CATEGORIA, TP_CATEGORIA, DS_CATEGORIA, DT_INICIO, DT_TERMINO, ST_CATEGORIA) 
VALUES (SQ_MC_CATEGORIA.NEXTVAL, 'P', 'Celular e Smartphone', TO_DATE('01042000','DDMMYYYY'), NULL, 'A');

INSERT INTO MC_CATEGORIA_PROD (CD_CATEGORIA, TP_CATEGORIA, DS_CATEGORIA, DT_INICIO, DT_TERMINO, ST_CATEGORIA) 
VALUES (SQ_MC_CATEGORIA.NEXTVAL, 'P', 'Colchões', TO_DATE('01052000','DDMMYYYY'), NULL, 'A');

INSERT INTO MC_CATEGORIA_PROD (CD_CATEGORIA, TP_CATEGORIA, DS_CATEGORIA, DT_INICIO, DT_TERMINO, ST_CATEGORIA) 
VALUES (SQ_MC_CATEGORIA.NEXTVAL, 'P', 'Esporte e Lazer', TO_DATE('01062000','DDMMYYYY'), NULL, 'A');

INSERT INTO MC_CATEGORIA_PROD (CD_CATEGORIA, TP_CATEGORIA, DS_CATEGORIA, DT_INICIO, DT_TERMINO, ST_CATEGORIA) 
VALUES (SQ_MC_CATEGORIA.NEXTVAL, 'P', 'Ferramentas', TO_DATE('01072000','DDMMYYYY'), NULL, 'A');

INSERT INTO MC_CATEGORIA_PROD (CD_CATEGORIA, TP_CATEGORIA, DS_CATEGORIA, DT_INICIO, DT_TERMINO, ST_CATEGORIA) 
VALUES (SQ_MC_CATEGORIA.NEXTVAL, 'P', 'Games', TO_DATE('01082000','DDMMYYYY'), NULL, 'A');

INSERT INTO MC_CATEGORIA_PROD (CD_CATEGORIA, TP_CATEGORIA, DS_CATEGORIA, DT_INICIO, DT_TERMINO, ST_CATEGORIA) 
VALUES (SQ_MC_CATEGORIA.NEXTVAL, 'P', 'Informática', TO_DATE('01092000','DDMMYYYY'), NULL, 'A');

INSERT INTO MC_CATEGORIA_PROD (CD_CATEGORIA, TP_CATEGORIA, DS_CATEGORIA, DT_INICIO, DT_TERMINO, ST_CATEGORIA) 
VALUES (SQ_MC_CATEGORIA.NEXTVAL, 'P', 'Livros', TO_DATE('01102000','DDMMYYYY'), NULL, 'A');

INSERT INTO MC_CATEGORIA_PROD (CD_CATEGORIA, TP_CATEGORIA, DS_CATEGORIA, DT_INICIO, DT_TERMINO, ST_CATEGORIA) 
VALUES (SQ_MC_CATEGORIA.NEXTVAL, 'P', 'Pet Shop', TO_DATE('01112000','DDMMYYYY'), NULL, 'A');

INSERT INTO MC_CATEGORIA_PROD (CD_CATEGORIA, TP_CATEGORIA, DS_CATEGORIA, DT_INICIO, DT_TERMINO, ST_CATEGORIA) 
VALUES (SQ_MC_CATEGORIA.NEXTVAL, 'P', 'TV e Utilidades Domésticas', TO_DATE('01122000','DDMMYYYY'), NULL, 'A');


/*h) Cadastre as seguintes categorias para os vídeos: Instalação do produto; Uso no cotidiano; Comercial com personalidade; entre outros.

Resposta do Comando SQL item h)

*/

INSERT INTO MC_CATEGORIA_PROD (CD_CATEGORIA, TP_CATEGORIA, DS_CATEGORIA, DT_INICIO, DT_TERMINO, ST_CATEGORIA) 
VALUES (SQ_MC_CATEGORIA.NEXTVAL, 'V', 'Instalação do produto', TO_DATE('10012005','DDMMYYYY'), NULL, 'A');

INSERT INTO MC_CATEGORIA_PROD (CD_CATEGORIA, TP_CATEGORIA, DS_CATEGORIA, DT_INICIO, DT_TERMINO, ST_CATEGORIA) 
VALUES (SQ_MC_CATEGORIA.NEXTVAL, 'V', 'Uso no cotidiano', TO_DATE('10032005','DDMMYYYY'), NULL, 'A');

INSERT INTO MC_CATEGORIA_PROD (CD_CATEGORIA, TP_CATEGORIA, DS_CATEGORIA, DT_INICIO, DT_TERMINO, ST_CATEGORIA) 
VALUES (SQ_MC_CATEGORIA.NEXTVAL, 'V', 'Comercial com personalidade', TO_DATE('1012005','DDMMYYYY'), NULL, 'A');

INSERT INTO MC_CATEGORIA_PROD (CD_CATEGORIA, TP_CATEGORIA, DS_CATEGORIA, DT_INICIO, DT_TERMINO, ST_CATEGORIA) 
VALUES (SQ_MC_CATEGORIA.NEXTVAL, 'V', 'Entre outros', TO_DATE('2402005','DDMMYYYY'), NULL, 'A');


/* i) Cadastre 20 produtos e associe as categorias adequadas ao produto. */

INSERT INTO MC_PRODUTO (CD_PRODUTO, CD_CATEGORIA, NR_CD_BARRAS_PROD, DS_PRODUTO, VL_UNITARIO, TP_EMBALAGEM, ST_PRODUTO, VL_PERC_LUCRO, DS_COMPLETA_PROD)
VALUES (SQ_MC_PRODUTO.NEXTVAL, 1, '1234567890123456789012345678901234567890', 'Gargantilha feito a mão , produto artesanal', 92, 'Plasitco', 'A', 50, 'Colar, gargantilha em cerâmica fria
Nas cores branca, preto, amarelo e ouro negro Cordão de algodão bege Fecho em couro regulável Comprimento 43 cm (regulável) Pingente 7 cm Peso 66 gramas Peça única Feito a mão Pronta entrega
Comprimento: 0.43 cm Peso: 66 g');

INSERT INTO MC_PRODUTO (CD_PRODUTO, CD_CATEGORIA, NR_CD_BARRAS_PROD, DS_PRODUTO, VL_UNITARIO, TP_EMBALAGEM, ST_PRODUTO, VL_PERC_LUCRO, DS_COMPLETA_PROD)
VALUES (SQ_MC_PRODUTO.NEXTVAL, 8, '1234567890123456789012345678901234568080', 'God of War Ragnarök', 206.99, 'Plasitco', 'A', 200, 'Jogo God of War Ragnarök, Edição Standard, PS4');

INSERT INTO MC_PRODUTO (CD_PRODUTO, CD_CATEGORIA, NR_CD_BARRAS_PROD, DS_PRODUTO, VL_UNITARIO, TP_EMBALAGEM, ST_PRODUTO, VL_PERC_LUCRO, DS_COMPLETA_PROD)
VALUES (SQ_MC_PRODUTO.NEXTVAL, 8, '1234567890123456789012345678901234569090', 'Elden Ring, Playstation 5', 732.54, 'Plasitco', 'A', 700, 'Elden Ring Playstation 5 - 722674130202');

INSERT INTO MC_PRODUTO (CD_PRODUTO, CD_CATEGORIA, NR_CD_BARRAS_PROD, DS_PRODUTO, VL_UNITARIO, TP_EMBALAGEM, ST_PRODUTO, VL_PERC_LUCRO, DS_COMPLETA_PROD)
VALUES (SQ_MC_PRODUTO.NEXTVAL, 8, '1234567890123456789012345678901234561010', 'The Last of Us Part I', 144.30, 'Plasitco', 'A', 100, 'The Last of Us Part I Sony para PS4, Naughty Dog');

INSERT INTO MC_PRODUTO (CD_PRODUTO, CD_CATEGORIA, NR_CD_BARRAS_PROD, DS_PRODUTO, VL_UNITARIO, TP_EMBALAGEM, ST_PRODUTO, VL_PERC_LUCRO, DS_COMPLETA_PROD)
VALUES (SQ_MC_PRODUTO.NEXTVAL, 8, '1234567890123456789012345678901234561010', 'The Last of Us Part II', 169.90, 'Plasitco', 'A', 130, 'The Last of Us Part II Sony para PS4, Naughty Dog');

INSERT INTO MC_PRODUTO (CD_PRODUTO, CD_CATEGORIA, NR_CD_BARRAS_PROD, DS_PRODUTO, VL_UNITARIO, TP_EMBALAGEM, ST_PRODUTO, VL_PERC_LUCRO, DS_COMPLETA_PROD)
VALUES (SQ_MC_PRODUTO.NEXTVAL, 8, '123456789012345678901234567890123456812', 'Jogo Dark Souls I', 141.80, 'Plasitco', 'A', 111, 'Jogo Dark Souls I: The Fire Fades Edition, PS4');

INSERT INTO MC_PRODUTO (CD_PRODUTO, CD_CATEGORIA, NR_CD_BARRAS_PROD, DS_PRODUTO, VL_UNITARIO, TP_EMBALAGEM, ST_PRODUTO, VL_PERC_LUCRO, DS_COMPLETA_PROD)
VALUES (SQ_MC_PRODUTO.NEXTVAL, 8, '123456789012345678901234567890123452132', 'Jogo Dark Souls II', 170.90, 'Plasitco', 'A', 129.99, 'Jogo Dark Souls II: The Fire Fades Edition, PS4');

INSERT INTO MC_PRODUTO (CD_PRODUTO, CD_CATEGORIA, NR_CD_BARRAS_PROD, DS_PRODUTO, VL_UNITARIO, TP_EMBALAGEM, ST_PRODUTO, VL_PERC_LUCRO, DS_COMPLETA_PROD)
VALUES (SQ_MC_PRODUTO.NEXTVAL, 8, '123456789012345678901234567890123456898', 'Jogo Dark Souls III', 240.02, 'Plasitco', 'A', 157.80, 'Jogo Dark Souls III: The Fire Fades Edition, PS4');

INSERT INTO MC_PRODUTO (CD_PRODUTO, CD_CATEGORIA, NR_CD_BARRAS_PROD, DS_PRODUTO, VL_UNITARIO, TP_EMBALAGEM, ST_PRODUTO, VL_PERC_LUCRO, DS_COMPLETA_PROD)
VALUES (SQ_MC_PRODUTO.NEXTVAL, 9, '1234567890123456789012345678901234561111', 'Processador AMD Ryzen 5 5600G', 2277.50 , 'Papelão', 'A', 2200, 'Processador AMD Ryzen 5 5600G, 3.9GHz (4.4GHz Max Turbo), 
Cache 19MB, 6 Núcleos, 12 Threads, Vídeo Integrado, AM4 - 100-100000252BOX');

INSERT INTO MC_PRODUTO (CD_PRODUTO, CD_CATEGORIA, NR_CD_BARRAS_PROD, DS_PRODUTO, VL_UNITARIO, TP_EMBALAGEM, ST_PRODUTO, VL_PERC_LUCRO, DS_COMPLETA_PROD)
VALUES (SQ_MC_PRODUTO.NEXTVAL, 9, '1234567890123456789012345678901234562222', 'SSD 240 GB Kingston A400', 211.754, 'Plasitco', 'A', 127.99, 'SSD 240 GB Kingston A400, SATA, Leitura: 500MB/s e 
Gravação: 350MB/s - SA400S37/240G');

INSERT INTO MC_PRODUTO (CD_PRODUTO, CD_CATEGORIA, NR_CD_BARRAS_PROD, DS_PRODUTO, VL_UNITARIO, TP_EMBALAGEM, ST_PRODUTO, VL_PERC_LUCRO, DS_COMPLETA_PROD)
VALUES (SQ_MC_PRODUTO.NEXTVAL, 9, '1234567890123456789012345678901234563223', 'Air Cooler Rise Mode Gamer G800', 159.99, 'Caixa', 'A', 90, 'Air Cooler Rise Mode Gamer G800, 180mm, RGB - RM-AC-O8-RGB');

INSERT INTO MC_PRODUTO (CD_PRODUTO, CD_CATEGORIA, NR_CD_BARRAS_PROD, DS_PRODUTO, VL_UNITARIO, TP_EMBALAGEM, ST_PRODUTO, VL_PERC_LUCRO, DS_COMPLETA_PROD)
VALUES (SQ_MC_PRODUTO.NEXTVAL, 9, '1234567890123456789012345678901234566767', 'Memória Kingston Fury Beast', 235.28, 'Caixa', 'A', 172.99, 'Memória Kingston Fury Beast, 8GB, 3200MHz, DDR4, CL16,
Preto - KF432C16BB/8');

INSERT INTO MC_PRODUTO (CD_PRODUTO, CD_CATEGORIA, NR_CD_BARRAS_PROD, DS_PRODUTO, VL_UNITARIO, TP_EMBALAGEM, ST_PRODUTO, VL_PERC_LUCRO, DS_COMPLETA_PROD)
VALUES (SQ_MC_PRODUTO.NEXTVAL, 10, '1234567890123456789012345678901234567123', 'O Senhor dos Anéis: As duas torres', 69.90, 'Caixa', 'A', 9.90, 'b As Duas Torres /b br / br / O segundo volume de 
O Senhor dos Anéis, mais importante épico de fantasia moderno, narra os caminhos separados seguidos pelos 
membros da Sociedade do Anel em sua luta para deter Sauron, o Senhor Sombrio da terra de Mordor, e destruir o Um Anel, no qual está contida a maior parte do poder do tirano demoníaco imaginado por
J.R.R. Tolkien. br / br / Um ataque-surpresa pôs fim à jornada conjunta da Sociedade do Anel. De um lado, o trio formado pelo elfo Legolas, pelo anão Gimli e por Aragorn, herdeiro da realeza dos Homens,
tenta resgatar os jovens hobbits Merry e Pippin, capturados por guerreiros-órquicos. A busca pelos companheiros perdidos levará os três a confrontar os cavaleiros do reino de Rohan e o mago renegado Saruman,
que também deseja o Um Anel para si. br / br / Enquanto isso, do outro lado das montanhas, Frodo e Sam buscam uma maneira de entrar em Mordor e chegar até a montanha onde o Anel foi forjado, único lugar onde
é possível destruí-lo. Para isso, acabam recebendo a ajuda de seu mais improvável aliado: Gollum, a criatura que chegou a ter o Anel sob seu poder durante centenas de anos e que ainda é devorada, em corpo e 
alma, pelo desejo de voltar a possuí-lo. br / br / Com cenas que mesclam o heroico e o intimista, o sublime e o cômico, As Duas Torres abriga algumas das criações mais inesquecíveis da imaginação de J.R.R. 
Tolkien, como os gigantescos Ents e a cultura nobre e belicosa do povo de Rohan.');

INSERT INTO MC_PRODUTO (CD_PRODUTO, CD_CATEGORIA, NR_CD_BARRAS_PROD, DS_PRODUTO, VL_UNITARIO, TP_EMBALAGEM, ST_PRODUTO, VL_PERC_LUCRO, DS_COMPLETA_PROD)
VALUES (SQ_MC_PRODUTO.NEXTVAL, 11, '12345678901234567890123456789012345661287', 'Ração Seca Nutrilus', 151.92, 'Saco', 'A', 100, 'Ração Seca Nutrilus Pro Carne para Cães Adultos 20kg');

INSERT INTO MC_PRODUTO (CD_PRODUTO, CD_CATEGORIA, NR_CD_BARRAS_PROD, DS_PRODUTO, VL_UNITARIO, TP_EMBALAGEM, ST_PRODUTO, VL_PERC_LUCRO, DS_COMPLETA_PROD)
VALUES (SQ_MC_PRODUTO.NEXTVAL, 11, '1234567890123456789012345678901234566211', 'Refeição Natural Zee.Dog', 87.90, 'Caixa', 'A', 49.99, 'Refeição Natural Zee.Dog Kitchen para Cães Adultos Sabor Carne');

INSERT INTO MC_PRODUTO (CD_PRODUTO, CD_CATEGORIA, NR_CD_BARRAS_PROD, DS_PRODUTO, VL_UNITARIO, TP_EMBALAGEM, ST_PRODUTO, VL_PERC_LUCRO, DS_COMPLETA_PROD)
VALUES (SQ_MC_PRODUTO.NEXTVAL, 4, '1234567890123456789012345678901234566123', 'iPhone 11 Apple 64GB', 4739.90, 'Caixa', 'A', 2879.10, 'iPhone 11 Apple 64GB Preto 6,1” 12MP iOS');

INSERT INTO MC_PRODUTO (CD_PRODUTO, CD_CATEGORIA, NR_CD_BARRAS_PROD, DS_PRODUTO, VL_UNITARIO, TP_EMBALAGEM, ST_PRODUTO, VL_PERC_LUCRO, DS_COMPLETA_PROD)
VALUES (SQ_MC_PRODUTO.NEXTVAL, 4, '1234567890123456789012345678901234566321', 'iPhone 11 Apple 128GB', 5200, 'Caixa', 'A', 3228.47, 'iPhone 11 Apple 128GB Branco 6,1” 12MP iOS');

INSERT INTO MC_PRODUTO (CD_PRODUTO, CD_CATEGORIA, NR_CD_BARRAS_PROD, DS_PRODUTO, VL_UNITARIO, TP_EMBALAGEM, ST_PRODUTO, VL_PERC_LUCRO, DS_COMPLETA_PROD)
VALUES (SQ_MC_PRODUTO.NEXTVAL, 4, '1234567890123456789012345678901234566213', 'iPhone 12 Apple 64GB', 5300, 'Caixa', 'A', 3190, 'iPhone 12 Apple 64GB Preto 6,1” 12MP iOS');

INSERT INTO MC_PRODUTO (CD_PRODUTO, CD_CATEGORIA, NR_CD_BARRAS_PROD, DS_PRODUTO, VL_UNITARIO, TP_EMBALAGEM, ST_PRODUTO, VL_PERC_LUCRO, DS_COMPLETA_PROD)
VALUES (SQ_MC_PRODUTO.NEXTVAL, 4, '1234567890123456789012345678901234566312', 'iPhone 12 Apple 128GB', 5300, 'Caixa', 'A', 3190, 'iPhone 12 Apple 128GB Cinza 6,1” 12MP iOS');

INSERT INTO MC_PRODUTO (CD_PRODUTO, CD_CATEGORIA, NR_CD_BARRAS_PROD, DS_PRODUTO, VL_UNITARIO, TP_EMBALAGEM, ST_PRODUTO, VL_PERC_LUCRO, DS_COMPLETA_PROD)
VALUES (SQ_MC_PRODUTO.NEXTVAL, 4, '1234567890123456789012345678901234566456', 'iPhone 13 Apple 64GB', 5300, 'Caixa', 'A', 3190, 'iPhone 13 Apple 64GB Preto 6,1” 12MP iOS');

INSERT INTO MC_PRODUTO (CD_PRODUTO, CD_CATEGORIA, NR_CD_BARRAS_PROD, DS_PRODUTO, VL_UNITARIO, TP_EMBALAGEM, ST_PRODUTO, VL_PERC_LUCRO, DS_COMPLETA_PROD)
VALUES (SQ_MC_PRODUTO.NEXTVAL, 4, '1234567890123456789012345678901234566456', 'iPhone 13 Apple 128GB', 5300, 'Caixa', 'A', 3190, 'iPhone 13 Apple 128GB Preto 6,1” 12MP iOS');


/*j) Cadastre 2 vídeos de produtos na tabela MC_SGV_PRODUTO_VIDEO e associe esses 2 vídeos em um único produto já cadastrado. Associe também as categorias adequadas ao vídeo.

Resposta do Comando SQL item j)

*/

INSERT INTO MC_SGV_PRODUTO_VIDEO (CD_PRODUTO, NR_SEQUENCIA, CD_CATEGORIA, VD_PRODUTO, TP_VIDEO_PROD, DS_PATH_VIDEO_PROD, ST_VIDEO_PROD) 
VALUES (8, 1, 8, NULL, 'DEMO', 'doc/sed/hurdedss.videos.com.br', 'A');

INSERT INTO MC_SGV_PRODUTO_VIDEO (CD_PRODUTO, NR_SEQUENCIA, CD_CATEGORIA, VD_PRODUTO, TP_VIDEO_PROD, DS_PATH_VIDEO_PROD, ST_VIDEO_PROD) 
VALUES (3, 2, 8, NULL, 'DEMO', 'doc/sed/hurdedss.videos.com.br', 'A');

/*k) Por fim, cadastre 5 visualizações de vídeos de produtos na tabela MC_SGV_VISUALIZACAO_VIDEO e associe a um cliente a seu critério.

Resposta do Comando SQL item k)

*/

INSERT INTO MC_SGV_VISUALIZACAO_VIDEO (CD_VISUALIZACAO_VIDEO, NR_CLIENTE, CD_PRODUTO, DT_VISUALIZACAO, NR_HORA_VISUALIZACAO, NR_MINUTO_VIDEO, NR_SEGUNDO_VIDEO)
VALUES (SQ_MC_SGV_VISUAL_PROD.NEXTVAL, 1,  8, TO_DATE('14012023','DDMMYYYY'), 13, 10, 11);

INSERT INTO MC_SGV_VISUALIZACAO_VIDEO (CD_VISUALIZACAO_VIDEO, NR_CLIENTE, CD_PRODUTO, DT_VISUALIZACAO, NR_HORA_VISUALIZACAO, NR_MINUTO_VIDEO, NR_SEGUNDO_VIDEO)
VALUES (SQ_MC_SGV_VISUAL_PROD.NEXTVAL, 2,  9, TO_DATE('09012023','DDMMYYYY'), 11, 09, 33);

INSERT INTO MC_SGV_VISUALIZACAO_VIDEO (CD_VISUALIZACAO_VIDEO, NR_CLIENTE, CD_PRODUTO, DT_VISUALIZACAO, NR_HORA_VISUALIZACAO, NR_MINUTO_VIDEO, NR_SEGUNDO_VIDEO)
VALUES (SQ_MC_SGV_VISUAL_PROD.NEXTVAL, 3,  10, TO_DATE('20022023','DDMMYYYY'), 02, 10, 32);

INSERT INTO MC_SGV_VISUALIZACAO_VIDEO (CD_VISUALIZACAO_VIDEO, NR_CLIENTE, CD_PRODUTO, DT_VISUALIZACAO, NR_HORA_VISUALIZACAO, NR_MINUTO_VIDEO, NR_SEGUNDO_VIDEO)
VALUES (SQ_MC_SGV_VISUAL_PROD.NEXTVAL, 4,  12, TO_DATE('03032023','DDMMYYYY'), 09, 12, 17);

INSERT INTO MC_SGV_VISUALIZACAO_VIDEO (CD_VISUALIZACAO_VIDEO, NR_CLIENTE, CD_PRODUTO, DT_VISUALIZACAO, NR_HORA_VISUALIZACAO, NR_MINUTO_VIDEO, NR_SEGUNDO_VIDEO)
VALUES (SQ_MC_SGV_VISUAL_PROD.NEXTVAL, 1,  8, TO_DATE('14012023','DDMMYYYY'), 16, 18, 54);

/*l) Confirme todas as transações pendentes (muito importante).

Resposta do Comando SQL item i)

*/

COMMIT;

/*m) Cadastre uma categoria de produto com status I(nativo).

Resposta do Comando SQL item m)

*/

INSERT INTO MC_CATEGORIA_PROD (CD_CATEGORIA, TP_CATEGORIA, DS_CATEGORIA, DT_INICIO, DT_TERMINO, ST_CATEGORIA) 
VALUES (SQ_MC_CATEGORIA.NEXTVAL, 'P', 'CURSOS', TO_DATE('06062022','DDMMYYYY'), NULL, 'I');

/*n) Cadastre um produto com status I(nativo).

Resposta do Comando SQL item n)

*/

INSERT INTO MC_PRODUTO (CD_PRODUTO, CD_CATEGORIA, NR_CD_BARRAS_PROD, DS_PRODUTO, VL_UNITARIO, TP_EMBALAGEM, ST_PRODUTO, VL_PERC_LUCRO, DS_COMPLETA_PROD)
VALUES (SQ_MC_PRODUTO.NEXTVAL, 17, '8884567890123456789012345678901234566456', 'SQL DA PROF RITA', 19000, 'VIRTUAL', 'I', 19000, 'CURSO DE SQL DO INICIANTE AO AVANÇADO DA RITA');


/*o) Selecione um específico funcionário e atualize o Cargo e aplique 12% de aumento de salário.

Resposta do Comando SQL item o)

*/

UPDATE MC_FUNCIONARIO 
SET DS_CARGO = 'CONSELHEIRA SENIOR', VL_SALARIO = VL_SALARIO * 1.12
WHERE CD_FUNCIONARIO = 2;

/*p) Atualize a descrição de uma categoria de produto a seu critério.

Resposta do Comando SQL item p)

*/

UPDATE MC_CATEGORIA_PROD 
SET DS_CATEGORIA = 'DVD'
WHERE CD_CATEGORIA = 2
;

/*q) Atualize o nome de um departamento a sua escolha, utilizando como filtro o nome do departamento antes de ser atualizado.

Resposta do Comando SQL item q)

*/

UPDATE MC_DEPTO
SET NM_DEPTO = 'TECNOLOGIA INFORMAÇÃO'
WHERE NM_DEPTO = 'LOGISTICA';

/*r) Atualize a data de nascimento de um cliente pessoa física. Defina a nova data como sendo 18/05/2002.

Resposta do Comando SQL item r)

*/

UPDATE MC_CLI_FISICA
SET DT_NASCIMENTO = TO_DATE('18052002','DDMMYYYY')
WHERE NR_CLIENTE = 1;

/*s) Atualize a descrição de uma categoria de vídeo a seu critério.

Resposta do Comando SQL item s)

*/

UPDATE MC_CATEGORIA_PROD
SET DS_CATEGORIA = 'Eletrônicos'
WHERE DS_CATEGORIA = 'Entre outros';


/*t) Desative um funcionário colocando o status como I(nativo) e também a data de desligamento como sendo a data de hoje (sysdate).

Resposta do Comando SQL item t)

*/

UPDATE MC_FUNCIONARIO
SET ST_FUNC = 'I', DT_DESLIGAMENTO = sysdate
WHERE CD_FUNCIONARIO = 2;

/*u) Cadastre um atendimento SAC na tabela MC_SGV_SAC. Após isso, utilize outro comando DML para atualizar a descrição detalhada de retorno do SAC feito pelo funcionário. Insira um conteúdo significativo.
Não se esqueça de atualizar também a data e hora de atendimento e também acrescendo o número total de horas do atendimento SAC.

Resposta do Comando SQL item u)

*/

INSERT INTO MC_SGV_SAC (NR_SAC, NR_CLIENTE, CD_PRODUTO, CD_FUNCIONARIO, DS_DETALHADA_SAC, DT_ABERTURA_SAC, HR_ABERTURA_SAC, DT_ATENDIMENTO, HR_ATENDIMENTO_SAC, NR_TEMPO_TOTAL_SAC, DS_DETALHADA_RETORNO_SAC, TP_SAC, ST_SAC, NR_INDICE_SATISFACAO)
VALUES (SQ_MC_SGV_SAC.NEXTVAL, 1, 1, 1, TO_CLOB('Cliente está informando sobre uma compra não autorizada no cartão'), sysdate, 2, NULL, NULL, NULL, TO_CLOB(''), 'E', 'E', 10);



UPDATE MC_SGV_SAC 
SET DS_DETALHADA_RETORNO_SAC = TO_CLOB('Finalizado o atendimento, cliente estava com o cartão clonado.')
WHERE NR_SAC = 1;


UPDATE MC_SGV_SAC
SET DT_ATENDIMENTO = sysdate, HR_ATENDIMENTO_SAC = 2
WHERE NR_SAC = 1;



UPDATE MC_SGV_SAC 
SET NR_TEMPO_TOTAL_SAC = 4 
WHERE NR_SAC = 1;

/*v) Selecione um endereço de cliente e coloque o status como I(nativo) e preencha a data de término como sendo a data de ontem. Utilize a função to_date para registrar esse novo valor da data.

Resposta do Comando SQL item v)

*/

UPDATE MC_END_CLI
SET ST_END = 'I', DT_TERMINO = TO_DATE('10042023','DDMMYYYY')
WHERE NR_CLIENTE = 1;

/*w) Selecione um endereço de funcionário e coloque o status como I(nativo) e preencha a data de término como sendo a data de ontem. Utilize a função to_date para registrar esse novo valor da data.

Resposta do Comando SQL item w)

*/

UPDATE MC_END_FUNC
SET ST_END = 'I', DT_TERMINO = TO_DATE('10042023','DDMMYYYY')
WHERE CD_FUNCIONARIO = 1;


/*x) Tente eliminar um estado que tenha uma cidade Cadastrada. Isso foi possível? Justifique o motivo?

Resposta do Comando SQL item x)


DELETE FROM MC_ESTADO WHERE SG_ESTADO = 'SP';

Relatório de erros - ORA-02292: restrição de integridade (RM551834.FK_MC_CIDADE_ESTADO) violada - registro filho localizado

Resposta: Não é possível eliminar um estado pois, ocorre uma restrição de integridade referencial que é violada ao tentar excluir ou atualizar um registro pai 
que tem um ou mais registros filhos associados. A mensagem de erro indica que a restrição de chave estrangeira com o nome "FK_MC_CIDADE_ESTADO" na tabela "RM551834" foi violada.*/

/*y) Selecione um produto e tente atualizar o status do produto com o status X. Isso foi possível? Justifique o motivo?

Resposta do Comando SQL item y)

*/


/*UPDATE MC_PRODUTO
SET ST_PRODUTO = 'X'
WHERE CD_PRODUTO = 1; 

ORA-02290: restrição de verificação (RM551834.CK_MC_PRODUTO_ST_PRODUTO) violada

Resposta: Não é possível pois quando uma restrição de verificação é violada ao inserir ou atualizar dados em uma tabela. Isso significa que a condição especificada na restrição não foi atendida.*/


/*z) Confirme todas as transações pendentes.

Resposta do Comando SQL item z)

*/

commit;






